### ISSUE TITLE
Missing changes in the npm package

### ISSUE THREAD

**Issue by ramrami** [4ern/laravel-mix-handlebars#4]
Hi,

I installed this package (v1.0.3) from npm but couldn't make it work (on linux). 
The changes made in this PR #3 are not present in the npm version. 

Thank you

**Comment by blackfyre** [comment]
Can confirm this problem

**Comment by tasinttttttt** [comment]
Fixed with:

- Delete `./node_modules`
- Delete`package-lock.json`
- Run `npm install --force` (to disable npm cache)

My guess is npm doesn't compare files but only versions, and as there was no version change between the fixes, your npm uses a cached version.

My suggestion to the maintainer is to either create a Release or to bump the version to 1.0.4

**Comment by tasinttttttt** [comment]
Hi @4ern could you publish the package on npm? npm still has the 1.0.3 version as the last package version
